Resources/Maps/_L5/Shuttles/cryptid.yml, Resources/Prototypes/_DV/Catalog/Shipyard/civilian.yml
Library shuttle? Don't mind if I do! Repurposes the SRV Crypted from the old shuttle events.
**Changelog**
:cl:
- add: Added the Cryptid library shuttle for purchase from the shipyard.
=> Add UNCS Cryptid as a purchasable ship.

Resources/Prototypes/Entities/Objects/Misc/books.yml, Resources/Prototypes/Entities/Objects/Misc/paper.yml, Resources/Prototypes/_DV/Entities/Objects/Devices/tape_recorder.yml
We want more roleplay stuff~
Fixes #11
Fixes #12
**Changelog**
:cl:
- tweak: Changed character counts of paper and books to 10k and 30k characters respectively.
- tweak: Upped cassette length to ten minutes.
=> Up the character counts of paper and books, recording time of cassettes

Content.Client/_DV/UserInterfaces/Systems/Chat/ChatUIController.cs, Resources/Changelog/DeltaVChangelog.yml, Resources/Prototypes/Catalog/Fills/Lockers/medical.yml, Resources/Prototypes/Entities/Mobs/Customization/Markings/scars.yml, Resources/Prototypes/_DV/Catalog/Fills/Lockers/medical.yml, Resources/Prototypes/_DV/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml, Resources/Prototypes/_DV/Entities/Objects/Weapons/Guns/Rifles/rifles.yml, Resources/Prototypes/_DV/Roles/Jobs/CentComm/EmergencyResponseTeam.yml, Resources/ServerInfo/Guidebook/Mobs/IPCs.xml
Upstream merges
* Vulp scars are unisex (because for some reason they weren't before
* ERT bug fixes
* Lady Elegance post-engi-rework fixes
* Minor invisible fixes
**Changelog**
=> Merge upstream 20250408

Resources/Locale/en-US/_DV/datasets/figurines.ftl, Resources/Maps/_DV/Nonstations/listening_post.yml, Resources/Prototypes/Entities/Objects/Devices/pda.yml, Resources/Prototypes/Entities/Objects/Misc/handy_flags.yml, Resources/Prototypes/Entities/Structures/Wallmounts/Signs/flags.yml
Yaml/FTL ops.
Typos and lore changes.
**Changelog**
=> Some more Lagrangfication

Resources/Maps/_L5/Shuttles/borough.yml, Resources/Maps/_L5/Shuttles/bufo.yml, Resources/Maps/_L5/Shuttles/cryptid.yml, Resources/Prototypes/GameRules/unknown_shuttles.yml, Resources/Prototypes/_DV/Catalog/Shipyard/civilian.yml, Resources/Prototypes/_L5/Catalog/Shipyard/civilian.yml
Driveby: make unknown shuttle events half as common.
Adds a few shuttles for purchase from the shipyard.
As a driveby, makes shuttle events half as common.
Foodtruck ops.
Mining? Partying? Why not both? Die on the red rock in luxury with this decked-out mining shuttle.
**Changelog**
:cl:
- add: Bufo and Borough shuttles now available for purchase!
- tweak: Shuttle events are half as common.
=> Add Borough and Bufo shuttles

Content.Server/_EE/Materials/MaterialSiloSystem.cs
(Ported from https://github.com/Simple-Station/Einstein-Engines/pull/1502)
I forgot about it.
---
:cl: Aviu00
- fix: Fix silo being out of range.
(cherry picked from commit 34c2bbca74b5a10d6a8466e728cc48b0acda5655)
**Changelog**
=> Port Fix Silo Distance from EE

Resources/Locale/en-US/_L5/reagents/meta/consumable/drink/drinks.ftl, Resources/Prototypes/Catalog/Cargo/cargo_food.yml, Resources/Prototypes/_L5/Catalog/Cargo/cargo_food.yml, Resources/Prototypes/_L5/Entities/Objects/Consumable/Drinks/drinks.yml, Resources/Prototypes/_L5/Recipes/Reactions/drinks.yml
Skunks: "Oh, don't worry, I tested it."
Reality:
* String fixes
* Recipe for lattes works
* Correct contents/name for the supplies crate 
* Drive-by: re-enable large pizza crates 
Some dumbass didn't test thoroughly enough
**Changelog**
:cl:
- fix: A bunch of small issues with the Sirius additions were addressed in one fell swoop
- tweak: Re-enabled large pizza crates
=> Dogstar fixes

Resources/Prototypes/_L5/Recipes/Reactions/drinks.yml
Fixed the recipes for hot choc and mocha in the guidebook
Awaaaa I am silly and also not great at this just yet. 
**Changelog**
:cl:
- fix: Dogstar mocha and hot choc recipes fixed
- tweak: Who makes hot choc with water??? Use milk instead.
=> Further Dogstar fixes

Resources/Prototypes/Entities/Mobs/base.yml, Resources/Prototypes/_L5/Recipes/Lathes/electronics.yml, Resources/Prototypes/_Shitmed/Recipes/Lathes/Packs/medical.yml, Resources/Prototypes/_Shitmed/Research/civilianservices.yml
* Omnimed Tool is back (but more expensive to research now)
* Massive contamination debuff
* Autoclave machine board is now researchable/printable
* Mobs no longer gib at 400 blunt. Salvagers rejoice.
Low pop dynamics are just different. You don't have a huge med team, surgery is often difficult because you aren't a surgeon or CMO, and our poor salvagers are brought back to the station only to fall to pieces. It's just...not fun for anyone.
YAML changes only
**Changelog**
:cl:
- add: (Re)added the Omnimed surgical multitool as tier 3 research
- add: Autoclave machine board researchable/printable
- tweak: Massive surgical contamination debuff
- tweak: bodies no longer gib  at 400 blunt
=> Lagrange™ brand med buff

Resources/Prototypes/Catalog/Fills/Lockers/heads.yml, Resources/Prototypes/Entities/Objects/Misc/paper.yml, Resources/Prototypes/Entities/Objects/Specific/Chemistry/chem_bag.yml, Resources/Prototypes/Entities/Objects/Specific/chemical-containers.yml, Resources/Prototypes/_L5/Catalog/Cargo/cargo_materials.yml, Resources/Prototypes/_L5/tags.yml
Small quality of life improvements relating to containers
* Paperwork belts can hold clipboards (including R&D and logi digiboards)
* SAdmin spawns with paperwork belt (you're an administrator, not an admiral) (but you still keep the sword because it's cool)
* Chem bags can hold jugs
* Can now order high cap water and fuel tanks
**Changelog**
:cl:
- tweak: Chem bags can hold jugs
- tweak: Paperwork belts can hold clipboards
- add: Station admin locker contains a paperwork belt for greater admin powers
- add: High cap water/fuel tanks can now be ordered from logi
=> Container QoL

Resources/Locale/en-US/_L5/research/experimental.ftl, Resources/Locale/en-US/_L5/research/industrial.ftl, Resources/Prototypes/Entities/Objects/Misc/candles.yml, Resources/Prototypes/Entities/Structures/Furniture/sink.yml, Resources/Prototypes/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/Entities/Structures/Specific/Janitor/drain.yml, Resources/Prototypes/Entities/Structures/Storage/Tanks/base_structuretanks.yml, Resources/Prototypes/Recipes/Lathes/Packs/clothing.yml, Resources/Prototypes/Recipes/Lathes/Packs/engineering.yml, Resources/Prototypes/Recipes/Lathes/Packs/science.yml, Resources/Prototypes/Recipes/Lathes/devices.yml, Resources/Prototypes/Recipes/Lathes/security.yml, Resources/Prototypes/Research/arsenal.yml, Resources/Prototypes/Research/civilianservices.yml, Resources/Prototypes/Research/experimental.yml, Resources/Prototypes/_DV/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/_L5/Recipes/Construction/Graphs/sinks-drains.yml, Resources/Prototypes/_L5/Recipes/Construction/sinks-drains.yml, Resources/Prototypes/_L5/Recipes/Crafting/Graphs/magic_candle.yml, Resources/Prototypes/_L5/Recipes/Crafting/magic_candle.yml, Resources/Prototypes/_L5/Recipes/Lathes/Packs/devices.yml, Resources/Prototypes/_L5/Recipes/Lathes/Packs/fabs.yml, Resources/Prototypes/_L5/Recipes/Lathes/Packs/science.yml, Resources/Prototypes/_L5/Recipes/Lathes/carpets.yml, Resources/Prototypes/_L5/Recipes/Lathes/devices.yml, Resources/Prototypes/_L5/Recipes/Lathes/electronics.yml, Resources/Prototypes/_L5/Research/experimental.yml, Resources/Prototypes/_L5/Research/industrial.yml, Resources/Prototypes/_L5/tags.yml
* Boards added to research
* Magic candles
* Missing carpet color added
* Force/tether/svalinn guns re-added
A lot of this is important for outpost gameplay, where you're building most things from scratch.
Fixes #76
Fixes #54
**Changelog**
:cl:
- add: Printable boards (techfab, monitoring consoles, biofab)
- add: The Svalinn, force gun, and tether gun are back!
- tweak: Magic candles can be crafted
- fix: Sky blue carpet can be printed
=> Massive update of manufacturables

Content.Server/Connection/ConnectionManager.cs
Like...I kinda get it, but also, it really threw us for a loop. We need actual whitelists, not hardcoded numbers of arbitrarily selected players to keep the peace.
**Changelog**
:cl:
- fix: Server whitelist now works
=> Undo DV's strange take on whitelists

Resources/Prototypes/_DV/Entities/Structures/Doors/airlock_groups.yml
Fixed the ability to paint standard airlocks medical theme
Seems like just an oversight.
Fixes #110 
**Changelog**
:cl:
- fix: Can now paint standard airlocks medical theme
=> Make medical airlocks paintable

Resources/Prototypes/Voice/disease_emotes.yml, Resources/Prototypes/_DV/Entities/Mobs/Player/kitsune.yml, Resources/Prototypes/_DV/Voice/speech_emote_sounds.yml, Resources/Prototypes/_DV/Voice/speech_emotes.yml
* Rodentia get the kitsune squeal as 'chitter'
* Kitsune get the full fox sound collection on hug, and can make the sounds with 'whine'
* Vulps get the kitsune bark as their scream
* 'yelp' and 'yip' lead to barking
* You can now sneeze
More sound variety = more better gameing
Fixes #100 
Fixes #101 
Fixes #102 
**Changelog**
:cl:
- tweak: Vulps now get a fox yell as a scream, rodentia can chitter, kitsune make all sorts of fox noises, and everyone can sneeze.
=> Update sounds for rodentia, kitsune, and vulps

Resources/Locale/en-US/_Impstation/nutrition/components/food-sequence.ftl, Resources/Locale/en-US/reagents/meta/consumable/food/condiments.ftl, Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/donkpocket.yml, Resources/Prototypes/Entities/Objects/Consumable/Food/burger.yml, Resources/Prototypes/Entities/Objects/Consumable/Food/ingredients.yml, Resources/Prototypes/Entities/Objects/Consumable/Food/soup.yml, Resources/Prototypes/Recipes/Cooking/meal_recipes.yml, Resources/Prototypes/_Impstation/Recipes/Cooking/food_sequence_element.yml, Resources/Prototypes/_Impstation/tags.yml
Skunks accidentally introduced a bunch of weird conflicts while Mae's branch was being landed whoops. Also there were some localization and prototype things that Imp introduced
**Changelog**
:cl:
- fix: Some food YAML/l10n errors fixed
=> Fix YAML/l10n errors in food

Resources/ConfigPresets/Build/development.toml, Resources/ConfigPresets/L5/L5.toml, Resources/ConfigPresets/L5/outpost.toml, Resources/ConfigPresets/L5/substations.toml, Resources/Locale/en-US/_L5/game_presets.ftl, Resources/Locale/en-US/_L5/research/industrial.ftl, Resources/Maps/_L5/nucleus.yml, Resources/Prototypes/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/_L5/Catalog/Cargo/cargo_science.yml, Resources/Prototypes/_L5/Catalog/Fills/Crates/science.yml, Resources/Prototypes/_L5/Recipes/Lathes/Packs/request_consoles.yml, Resources/Prototypes/_L5/Recipes/Lathes/electronics.yml, Resources/Prototypes/_L5/Research/industrial.yml, Resources/Prototypes/_L5/game_presets.yml, Resources/manifest.yml
* Added "Outpost" game preset, which is just the basic roundstart map variations, no glimmer or ghost roles (we can `addgamerule` those in-round)
* Added config presets for the two servers we have so far and updated the manifest to reflect this
* Linked previously unlinked atmos devices to air alarm on Nucleus
* Added researchable departmental cargo request consoles (fixes #96)
* Added purchaseable bluespace, a stopgap before we really tackle #135
**Changelog**
:cl:
- add: Outpost is now a game preset, which is forced on the outpost server and not in the vote list for the substations server.
- add: Request consoles are now researchable and printable
- fix: Vent/scrubber are linked on the Nucleus
- add: You can now purchase three bluespace crystals for 15,000 RACs
=> Outpost followup 1 of ???

.github/workflows/build-map-renderer.yml, .github/workflows/build-test-debug.yml, .github/workflows/changelog.yml, .github/workflows/close-master-pr.yml, .github/workflows/labeler-conflict.yml, .github/workflows/labeler-pr.yml, .github/workflows/test-packaging.yml, .github/workflows/update-credits.yml, .github/workflows/validate-rgas.yml, .github/workflows/validate_mapfiles.yml, .github/workflows/yaml-linter.yml, Resources/Maps/_L5/nucleus.yml, Resources/Prototypes/_L5/Catalog/Shipyard/civilian.yml, Tools/dump_github_contributors.ps1
Github workflows have been updated for Lagrange. There may be some more pushes to this branch as I check and make sure everything is alright.
**Changelog**
=> Update workflows for L5

Content.IntegrationTests/Tests/PostMapInitTest.cs, Content.Shared/_L5/Traits/Synthetic/SharedSynthSystem.cs, Resources/ConfigPresets/L5/L5.toml, Resources/Maps/_L5/nucleus.yml, Resources/Prototypes/Entities/Objects/Misc/candles.yml, Resources/Prototypes/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/_L5/Maps/nucleus.yml, Resources/Prototypes/_L5/Recipes/Lathes/Packs/fabs.yml
Hopefully getting all of the things the integration tests are tripping over. Running them locally is a bit of a mess, so...
**Changelog**
=> Build fixes

Resources/Changelog/DeltaVChangelog.yml, Resources/Locale/en-US/_Impstation/reagents/meta/medicine.ftl, Resources/Maps/_DV/centcomm.yml, Resources/Prototypes/Recipes/Construction/Graphs/utilities/solarpanel.yml, Resources/Prototypes/_DV/Entities/Mobs/Player/kitsunefox.yml, Resources/Prototypes/_DV/Recipes/Construction/structures.yml, Resources/Prototypes/_Impstation/Recipes/Reactions/medicine.yml, Resources/Prototypes/_Impstation/reagents/medicine.yml
* Add Caramexinin, which lets animal stomachs process theobromine (watch out, Dogstar...)
* Crafting for directional (reinforced) uranium windows
* Easy-upgrade solars (go from plasma to uranium, etc)
* CC cloning improvements
**Changelog**
=> Merge upstream 2025-04-29

Resources/ConfigPresets/L5/L5.toml, Resources/Locale/en-US/_DV/guidebook/guides.ftl, Resources/Locale/en-US/_L5/guidebook/guides.ftl, Resources/Prototypes/_L5/Guidebook/rules.yml
This effectively removes the respawn timer, allowing players to respawn as soon as they ghost.
Resolves #162
Resolves #159 
**Changelog**
:cl:
- tweak: Respawn timer is now set to 0 seconds down from 1200.
- tweak: Admins now show in the player count in the launcher
- fix: L5Ruleset now linked properly
=> Config update sweep

Content.Server/Chat/Systems/ChatSystem.cs
Speech broke because I guess I hit undo before committing.
**Changelog**
=> Typo ops :c

Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/misc.yml, Resources/Prototypes/Entities/Objects/Consumable/Food/ingredients.yml, Resources/Prototypes/Entities/Objects/Consumable/Food/meals.yml, Resources/Prototypes/Nyanotrasen/Entities/Objects/Consumable/Food/Baked/misc.yml, Resources/Prototypes/Nyanotrasen/Entities/Objects/Consumable/Food/Baked/pizza.yml, Resources/Prototypes/Nyanotrasen/Entities/Objects/Consumable/Food/meals.yml, Resources/Prototypes/Nyanotrasen/Entities/Objects/Consumable/Food/salad.yml, Resources/Prototypes/Nyanotrasen/Entities/Objects/Consumable/Food/snacks.yml, Resources/Prototypes/_NF/Entities/Objects/Consumable/Food/meals.yml
Finally found the foods mentioned in issue #157 also getting rid of the meth and other chems in the melon fruit bowl for issue #195. Probably needs oversight bc idk shit about the dietary restrictions and I was kinda just looking for the ones mentioned
=> Food rebalance rebalance

Content.Client/Medical/CrewMonitoring/CrewMonitoringNavMapControl.cs, Content.Client/Medical/CrewMonitoring/CrewMonitoringWindow.xaml, Content.Client/Medical/CrewMonitoring/CrewMonitoringWindow.xaml.cs, Content.Server/Medical/SuitSensors/SuitSensorSystem.cs, Resources/Prototypes/Entities/Objects/Specific/Medical/handheld_crew_monitor.yml
Removed station bound component for handheld crew monitors.
Paramedic gaming.
Removed station bound component for handheld crew monitors.
Haven't properly tested offline but this is how you fix it in-game in VV.
**Changelog**
:cl:
- fix: Hand-held crew monitors work again.
=> fix: Make handheld crew monitors work again

Resources/Prototypes/Entities/Objects/Consumable/Food/burger.yml, Resources/Prototypes/Entities/Objects/Consumable/Food/meals.yml, Resources/Prototypes/Entities/Objects/Consumable/Food/soup.yml, Resources/Prototypes/Entities/Objects/Consumable/Food/taco.yml, Resources/Prototypes/Nyanotrasen/Entities/Objects/Consumable/Food/ingredients.yml
I just commented out the carpotoxin and adjusted the nutrient values to compensate. This one's on me for not thinking critically about the change the imp people made here.  We've figured out fugu irl we can figure out how to make sashimi not almost-lethal in space future, the microwave denatures the poison idfk.
Also I feel like imp missed a lot of the foods that have been in for a while I should go tweak those too if I ever have the energy for that
**Changelog**
:cl:
- remove: Removed death from fish-based dishes
=> Removed carpotoxin from the carp-based dishes

Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml
Use Wizden's enforcer sprites instead of Delta's.
Leonia said so.
**Changelog**
:cl:
- tweak: The enforcer is back to its old sprite.
=> tweak: Go back to the old enforcer sprite

Resources/Prototypes/Roles/Jobs/Civilian/mime.yml
Why indeed...
**Changelog**
:cl:
- fix: Mimes no longer have forced French accents
=> Remove French accent from mimes

Content.Shared/_L5/Traits/Synthetic/SharedSynthSystem.cs, Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml, Resources/Prototypes/Entities/Mobs/NPCs/silicon.yml, Resources/Prototypes/Voice/speech_emotes.yml, Resources/Prototypes/_EE/Entities/Mobs/Player/silicon_base.yml, Resources/Prototypes/_EE/Voice/speech_emotes.yml, Resources/Prototypes/_L5/tags.yml
Added a `Synth` tag to allow whitelisting emotes for synths without messing up the current `SiliconEmote` tag restrictions for other entities
Synths go beep :c
**Changelog**
:cl:
- fix: Synths can go beep again
=> Allow synths to beep

Resources/Prototypes/Voice/disease_emotes.yml, Resources/Prototypes/Voice/speech_emote_sounds.yml, Resources/Prototypes/_EE/Voice/speech_emotes.yml
Some EE punctuation and emote categorization, plus add whirr and boops to borgs.
Borg gaming.
Yaml ops.
**Changelog**
=> Adjust borg/IPC/synth emote usability

Resources/Prototypes/Body/Organs/Animal/animal.yml, Resources/Prototypes/Body/Organs/arachnid.yml, Resources/Prototypes/Body/Organs/human.yml, Resources/Prototypes/_Shitmed/Body/Organs/Animal/animal.yml
Make organs recyclable, except for brains (except for animal brains).
Fixes #78.
Yaml ops.
**Changelog**
- tweak: Most organs are now recyclable, if you don't feel like selling them.
=> tweak: make most organs recyclable

Content.Server/_DV/Cargo/Systems/CargoSystem.ATS.cs, Resources/Locale/en-US/_L5/roles/outpost.ftl, Resources/Maps/_L5/nucleus.yml, Resources/Prototypes/Entities/Stations/base.yml, Resources/Prototypes/Roles/Jobs/departments.yml, Resources/Prototypes/_DV/planets.yml, Resources/Prototypes/_L5/Entities/Markers/Spawners/jobs.yml, Resources/Prototypes/_L5/Entities/Objects/Devices/pda.yml, Resources/Prototypes/_L5/Maps/nucleus.yml, Resources/Prototypes/_L5/Roles/outpost.yml
* Updated lockers on the Nucleus
* Added Principal Architect role for the one who's designing the station
* Lowered salvage magnet cooldown to 30 seconds
* Made Lavaland, Glacier surface, and ATS FTL-able.
Resolves #211 (I think Outpost is the only game mode where this is required)
Resolves #210 
Resolves #83 
**Changelog**
:cl:
- tweak: Salvage magnet cooldown is now 30s
- tweak: Nucleus map updated with more lockers
- tweak: Other shuttles can now FTL to the ATS
- add: New principal architect role for Outpost rounds for the one in charge of station design
=> Outpost followup 2

Content.Server/Silicons/Borgs/BorgSwitchableTypeSystem.cs, Content.Shared/Silicons/Borgs/SharedBorgSystem.cs, Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml, Resources/Prototypes/Entities/Mobs/Cyborgs/borg_chassis.yml, Resources/Prototypes/Recipes/Lathes/Packs/robotics.yml, Resources/Prototypes/_L5/Recipes/Lathes/robotics.yml
Increase borg module limit to 20 across the board, disable any borg module whitelists, and re-enable printing of chassis default borg modules.
Long rounds means it doesn't make sense to lock borgs out of content. Self healing because IPCs get it so we should to—also it allows solo-salv borg to be more viable.
**Changelog**
:cl:
- remove: The borg module whitelist is no more.
- add: Borgs can now fit many more modules.
- add: You can now print borg modules that normally come with a selected chassis.
- tweak: Borgs can now weld themselves.
=> Big Borg Buff Bonanza

Content.Client/Chat/Managers/ChatManager.cs, Content.Client/Input/ContentContexts.cs, Content.Client/Options/UI/Tabs/KeyRebindTab.xaml.cs, Content.Client/UserInterface/Systems/Chat/ChatUIController.cs, Content.Client/UserInterface/Systems/Chat/Controls/ChannelFilterPopup.xaml.cs, Content.Client/UserInterface/Systems/Chat/Controls/ChannelSelectorButton.cs, Content.Client/UserInterface/Systems/Chat/Controls/ChannelSelectorPopup.cs, Content.Client/_L5/Traits/HardOfHearing/SignLanguageSystem.cs, Content.Server/Chat/Systems/ChatSystem.cs, Content.Server/_Floof/Speech/Components/RandomBarkComponent.cs, Content.Server/_Floof/Speech/Systems/RandomBarkSystem.cs, Content.Server/_L5/Chat/Commands/SignCommand.cs, Content.Server/_L5/Chat/Systems/ChatSystem.Sign.cs, Content.Shared/Chat/ChatChannel.cs, Content.Shared/Chat/ChatChannelExtensions.cs, Content.Shared/Chat/ChatSelectChannel.cs, Content.Shared/Chat/SharedChatSystem.cs, Content.Shared/Input/ContentKeyFunctions.cs, Content.Shared/_L5/CCVar/CCVars.L5.cs, Content.Shared/_L5/Traits/HardOfHearing/HardOfHearingComponent.cs, Content.Shared/_L5/Traits/HardOfHearing/SharedSignLanguageSystem.cs, Content.Shared/_L5/Traits/HardOfHearing/SignLanguageComponent.cs, Resources/Locale/en-US/_L5/chat/managers/chat-manager.ftl, Resources/Locale/en-US/_L5/traits/traits.ftl, Resources/Prototypes/_L5/Entities/Mobs/NPCs/debug.yml, Resources/Prototypes/_L5/Traits/disabilities.yml, Resources/Prototypes/_L5/Traits/speech.yml, Resources/keybinds.yml
This adds a hard of hearing/deaf trait, sign language as a form of communication, and a sign language skill triat.
Good disability RP mechanics, and something to help for not being able to speak in vacuum.
Resolves #29 (the end goal, at least; the EE language system is not well written)
https://www.youtube.com/watch?v=kCnfsfM9gxY
**Changelog**
:cl:
- add: Hard of hearing disability trait
- add: Sign language skill trait
=> Add hard of hearing trait and sign language

Content.Shared/_L5/Movement/Components/PilotOnBuckleComponent.cs, Content.Shared/_L5/Movement/Systems/PilotOnBuckleSystem.cs, Resources/Prototypes/_L5/Entities/Objects/Vehicles/Wheelchairs/BaseWheelchair/base_wheelchair.yml
Title, also door bump opener. Also simplifies the main comp slightly.
Accessibility good.
Modeled off of MechSystem.
**Changelog**
:cl:
- add: Wheelchairs will now have the same access level as their rider.
=> Feat: give wheelchairs the access of its rider

Content.Client/UserInterface/Systems/Chat/ChatUIController.cs
Removes the ability to see dead chat when you're in-round but still adminned.
As we run events for each other or discuss goings on, we've found it frustrating that those who are playing can see this (often very spoilery) chatter. The meta has become "go somewhere with no players and use LOOC," but like...dead chat is right there, and we treat the admin bit as a way to engage with the game in a mode that most servers don't
**Changelog**
:cl:
- tweak: admins in-round can no longer see dead chat
=> Remove admin check for dead chat

Resources/Prototypes/Reagents/Consumable/Food/ingredients.yml
i just switched to rider be nice to me im sorry i repent for my pepper crimes and im sorry for polluting the github
=> Repenting for my pepper crimes but I don't fuck up this time

Resources/ConfigPresets/L5/L5.toml
Enable battlemaps.
Server crash gaming.
**Changelog**
=> tweak: permanently enabled battlemaps

Content.Server/_L5/Traits/DietaryRestriction/DietaryRestrictionSystem.cs
Trying to keep everything in a single if statement was causing more problems than it was worth :P
**Changelog**
:cl:
- fix: Skunk™ brand logic removed from dietary restriction whitelists and replaced with actual logic
=> Clarify whitelist logic

Resources/Prototypes/Stacks/Materials/parts.yml, Resources/Prototypes/Stacks/floor_tile_stacks.yml, Resources/Prototypes/_Nuclear14/Stacks/floor_tile_stacks.yml
Rods max stack 30 > 60
Feels silly to push such a small change but w/e. I guess if there are any other stacks that people feel could be adjusted this is a good spot to stick them. Nothing jumped out at me though
=> Rod lovers united

Resources/Prototypes/Loadouts/loadout_groups.yml, Resources/Prototypes/_L5/Loadouts/trinkets.yml
=> feat: Add orb as loudout trinket

Resources/ConfigPresets/L5/L5.toml
Increase job length ccvar.
Allow silly job titles like "Guardian of the Great Toy Cupboard" or "System Consortium Administrator". ;)
Fixes #204.
**Changelog**
=> fix: increase max job length

Resources/Prototypes/_DV/typing_indicator.yml
loloops
Cat gaming.
Yaml warops.
**Changelog**
=> fix: felinid typing indicators

Content.Server/_DV/Cargo/Systems/CargoSystem.ATS.cs, Content.Server/_DV/Shuttles/Systems/DockingShuttleSystem.cs, Content.Shared/_L5/Shuttles/Components/FTLDestinationComponent.cs, Resources/Prototypes/_DV/planets.yml
Tweak our custom FTL logic to work a bit better with both piloted shuttles and auto-docking shuttles.
Gaming.
It Code.
**Changelog**
=> fix: FTL whitelist tweaks

Content.Client/Lathe/UI/LatheMenu.xaml
Move button to be in right thing.
Fixes #310.
**Changelog**
=> fix: ore processor claim points UI

Resources/Prototypes/Nyanotrasen/Entities/Structures/Research/oracle.yml, Resources/Prototypes/Nyanotrasen/Entities/Structures/Research/sophicscribe.yml
This unplugs the sophic grammateus and Oracle statues from any functionality and gives them flavor text that matches our setting. They remain a little mystical, though, because they're a) usually placed in chapels and b) that's friggin cool.
Resolves #315 
**Changelog**
:cl:
- tweak: Oracle and sophic grammateus are now merely statues
=> Repurpose R&D statues

Resources/Prototypes/Entities/Markers/Spawners/Random/Salvage/spawners.yml, Resources/Prototypes/_L5/Entities/Objects/Misc/land_mine.yml
Don't worry about it. :)
Don't worry about it. :)
<details>
<summary>Spoiler</summary>
</details>
**Changelog**
Don't worry about it. :)
=> feat: adjust salvage landmines

Content.Server/_DV/Objectives/Systems/KillFellowTraitorObjectiveSystem.cs
(cherry picked from commit 6b94d37925bf48cb37cd12d2848f56f71c81afd4)
Cherry-pick out the fix for the kill-other-traitor objective since the flakey test failure it causes is annoying.
**Changelog**
=> fix: bring back kill traitor objectives 

.github/workflows/labeler-pr.yml
Via https://www.github.com/googleapis/release-please-action/issues/1105#issuecomment-2780292262
**Changelog**
=> Attempt to fix the labeler workflow

Resources/Prototypes/Entities/Objects/Consumable/Food/soup.yml, Resources/Prototypes/Nyanotrasen/Entities/Objects/Consumable/Food/ingredients.yml, Resources/Prototypes/Nyanotrasen/Entities/Objects/Consumable/Food/salad.yml, Resources/Prototypes/Nyanotrasen/Entities/Objects/Consumable/Food/soup.yml, Resources/Prototypes/_DV/Entities/Objects/Consumable/Food/soup.yml, Resources/Prototypes/_DV/Recipes/Cooking/meal_recipes.yml, Resources/Prototypes/_NF/Entities/Objects/Consumable/Food/meals.yml, Resources/Prototypes/_NF/Entities/Objects/Consumable/Food/meat.yml, Resources/Prototypes/_NF/Entities/Objects/Consumable/Food/produce.yml
Soooo porting the food rebalance from imp caused a lot of issues and my attempts to fix those issues caused more issues and I wanted to make sure all the foods got tweaked. I don't think I'm done and someone not stupid should for Sure look this over to make sure I didn't fuck something up.
Also in the process of making these adjustments I realized previous adjustments I'd made were sort of ridiculous and so I've gone from "Let's match the ingredients volume" to "Let's just do what feels right". Directly matching the amount of stuff that goes into a recipe gets out of hand really fast, it turns out. I just tried to make a meal a meal, so there's less "One hungry person clears out the entire kitchen menu in seconds.".
I also tried to add in dietary restriction tags where ever I was like …
=> More food tweaks

Resources/Prototypes/_DV/Procedural/biome_ore_templates.yml, Resources/Prototypes/_DV/Procedural/salvage_loot.yml, Resources/Prototypes/_DV/planets.yml
We're getting bluespace from research. Also this was just way too common.
Resolves #247 
**Changelog**
:cl:
- remove: Bluespace ore has been removed in favor of bluespace from research.
=> Remove bluespace ore from biome

Content.Shared/_L5/Traits/HardOfHearing/SignLanguageSystem.cs
Title.
Ghosts are death; it makes sense.
**Changelog**
:cl:
- tweak: Ghosts now understand sign language
=> feat: ghosts know sign language

Resources/Prototypes/_L5/Maps/nucleus.yml
Disabled passive income for outpost rounds.
Leonia said it was fine.
**Changelog**
They'll figure it out.
=> feat: disable passive income for outpost rounds

Resources/ConfigPresets/L5/L5.toml
Stuff learned from current Outpost round:
* We don't want everyone to be able to sign
* We do want sign to respect line of sight
* We do want to be able to talk in space\*
\* Lore: short-range radio in hardsuits, but would be nice to make this more robust; if you're in a vacuum and wearing a hardsuit, only those in range and in a hardsuit (maybe even only in LOS) can hear you
Player polls in game and on Discord.
**Changelog**
:cl:
- tweak: Sign language now works as desired at round start.
- tweak: Went back to being able to talk in vacuum.
=> Update cvars for sign language

Resources/Prototypes/Procedural/vgroid.yml
Whoops!
Fixes #247 for real
**Changelog**
:cl:
- fix: Bluespace ore *actually* removed from red rock this time.
=> Nix bluespace from red rock

Content.Server/Nyanotrasen/Psionics/PsionicsSystem.cs
This removes round-start psionic rolling. It does not remove psionics from mimes or other inherent psionics.
Psionics are goin' awayyyy.
**Changelog**
:cl:
- remove: Psionics will no longer roll at round start
=> Remove psionic rolling

Resources/Prototypes/Nyanotrasen/Voice/speech_emote_sounds.yml, Resources/Prototypes/Voice/speech_emote_sounds.yml, Resources/Prototypes/_DV/Voice/speech_emote_sounds.yml
No more "hu hu hu"
**Changelog**
:cl:
- fix: Laughs no longer goes 'hu hu hu' sometimes.
=> fix: Reduce pitch variance

Resources/Locale/en-US/traits/traits.ftl
My friend said they like "can't speak" better, but agreed on the trait name.
**Changelog**
no
=> tweak: change wording of nonspeaking trait again

Content.Server/GameTicking/Commands/GoLobbyCommand.cs
Title.
It is crazy that this is the first time SOMEONE fell for it (haha wonder who) and that it was the one time that we were literally about to end the round anyway.
Might upstream idk.
Could also be based on if release build or not instead of time.
Also this will merge conflict when we get localized commands from upstream so, sorry.
**Changelog**
=> feat: add confirm to /golobby on > 1 hour rounds

Content.Shared/_L5/Materials/OreSilo/SharedOreSiloSystem.cs
Fix lathes.
I thought we could remove them but apparently people use them.
**Changelog**
=> fix: only ore silo sources should be ore silo sources

Content.Client/Cargo/BUI/CargoOrderConsoleBoundUserInterface.cs, Content.Client/Cargo/UI/CargoConsoleMenu.xaml.cs, Content.Server/Cargo/Systems/CargoSystem.Funds.cs, Content.Server/Cargo/Systems/CargoSystem.Orders.cs, Resources/ConfigPresets/L5/L5.toml, Resources/Locale/en-US/cargo/cargo-console-component.ftl, Resources/Prototypes/Entities/Stations/base.yml, Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
Kill departmental economy.
Fixes #331.
Still leaves departmental order consoles because they're cool.
**Changelog**
:cl:
- remove: Departmental economy is no more. (Order consoles still exist, and will all pull from the same bank account.)
=> feat: disable departmental economy

Content.Shared/Nutrition/Components/HungerComponent.cs, Content.Shared/Nutrition/Components/ThirstComponent.cs, Resources/Prototypes/Entities/Mobs/Species/arachnid.yml, Resources/Prototypes/Entities/Mobs/Species/diona.yml, Resources/Prototypes/_DV/Entities/Mobs/Species/chitinid.yml, Resources/Prototypes/_DV/Entities/Mobs/Species/feroxi.yml, Resources/Prototypes/_DV/Entities/Mobs/Species/rodentia.yml
I could have gotten rid of it, but I want to iterate on it, I think.
**Changelog**
:cl:
- tweak: Hunger and thirst suck less.
=> Nerf hunger and thirst rates

Content.Client/Parallax/Data/ParallaxLayerConfig.cs, Content.Client/Parallax/ParallaxOverlay.cs
Title.
Needed for some stuff further down the line that I'm working on.
**Changelog**
Not user facing
=> feat: pass CurTime to parallax shaders if requested

Resources/Prototypes/_L5/Catalog/Shipyard/civilian.yml
Evil shuttle selling meta rahh
https://github.com/lagrange14/substations/actions/runs/15911555833/job/44879920116#step:10:15
**Changelog**
=> tweak: another shuttle arbitrage tweak

Resources/Prototypes/_DV/Entities/Mobs/Customization/Markings/feroxi.yml, Resources/Prototypes/_Impstation/Entities/Mobs/Species/thaven.yml, Resources/Prototypes/_Impstation/Species/thaven.yml
A thaven is a kind of fish that dreams.
Holy Mind misses her tail.
**Changelog**
:cl:
- add: Thaven get tails
=> Give thaven tails

Content.Server/_DV/Silicons/Laws/SlavedBorgSystem.cs
Don't crash the server when you open the type selection menu for borgs.
Yeah I don't totally get why this fixes it either.
**Changelog**
=> Fix server crash on borg type selection

Resources/Prototypes/Entities/Mobs/NPCs/animals.yml, Resources/Prototypes/Entities/Mobs/NPCs/scurret.yml, Resources/Prototypes/_L5/Body/Prototypes/scurret.yml
Title.
Fixes #373.
Forgot to take a screenshot of Motes standing around a field of dead scurrets and monkeys bleeding rivers of blood. Oh well; there's always next time.
**Changelog**
=> fix: fix scurrets gibbing into monkeys

Content.Shared/_L5/SubFloor/SubFloorHideComponent.cs
Make vent hiding have persistence.
Bug.
I was silly and didn't make the thing a datafield.
**Changelog**
=> fix: serialize SubFloorHideComponent.Enabled

Resources/Maps/_L5/omphalos.yml, Resources/Prototypes/Entities/Structures/Machines/smartfridge.yml, Resources/Prototypes/_L5/Entities/Structures/Machines/foodfridge.yml
Mapping updates from first playthrough
Resolves #414
Resolves #415 
Resolves #421
Also fixes some issues with the smartfridge whitelist and removes its advertise dataset (AdvertiseComponent is no more).
**Changelog**
=> Omphalos updates first pass

Content.Server/_DV/AACTablet/AACTabletSystem.cs
=> fix: Admin log AAC tablet messages

Content.Server/Chat/Systems/ChatSystem.cs
Fixie AI not hearing through hoload
Fixes #432.
We were measuring distance to AI core for sound in space checks but AI core has a custom override anyway for determining if it can hear stuff, so just exempt it.
**Changelog**
:cl:
- fix: SSR can hear people through holopads again.
=> fix: SSR can hear through holopads again

Resources/ConfigPresets/L5/L5.toml
We have one now
Discord exists, unfortunately, but at least we are pretty
Idk how to test this, tbh, but it's just what DV had except with our icon ID
**Changelog**
=> feat: Add discord rich icon

Content.Server/_L5/StaticField/StaticFieldSystem.cs, Content.Shared/_L5/StaticField/StaticFieldComponent.cs, Resources/Audio/_L5/Effects/StaticField/attributions.yml, Resources/Prototypes/_L5/Entities/Structures/Holographic/projections.yml
Responding to @perryprog 's sniped review on #438
**Changelog**
=> chore: Clean up C# side of static fields

Resources/Locale/en-US/_L5/traits/traits.ftl, Resources/Prototypes/_DV/Entities/Mobs/Species/vulpkanin.yml, Resources/Prototypes/_L5/Traits/physical_traits.yml
Now Motes can drink from a bucket like a stupid idiot dog and spill everywhere
Driveby on two typos
**Changelog**
:cl:
- add: Messy drinker trait selectable by everyone (no longer on by default for vulps)
=> feat: Move messy drinker to a trait

Resources/Prototypes/Catalog/Fills/Lockers/service.yml
Resolves #441 
**Changelog**
:cl:
- add: Jani lockers come with a mop bucket cube and a bucket
=> feat: Add buckets to janilocker

Resources/Locale/en-US/_L5/recipes/structures.ftl, Resources/Prototypes/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/Entities/Structures/Walls/walls.yml, Resources/Prototypes/Recipes/Construction/Graphs/structures/girder.yml, Resources/Prototypes/_L5/Recipes/Construction/structures.yml, Resources/Prototypes/_L5/Recipes/Lathes/Packs/ore.yml, Resources/Prototypes/_L5/Recipes/Lathes/sheet.yml
Build parity, used for #447 
**Changelog**
:cl:
- add: Stone/sandstone walls are now buildable.
- add: Brass can be made in the industrial ore refiner.
=> feat: Craftable (sand)stone walls and printable brass
