- Resources/Prototypes/Entities/Structures/Machines/holopad.yml
Holopad fixture is no longer hard, meaning you can drag stuff over it.
Tech is advanced enough to recess things in the floor.
**Changelog**
:cl:
- fix: Holopads can have stuff dragged over them now.
> Make holopads passable by dragged items

- Resources/Prototypes/Recipes/Lathes/Packs/engineering.yml
- Resources/Prototypes/Recipes/Lathes/electronics.yml
- Resources/Prototypes/Research/industrial.yml
The power monitor board was put back where it belongs and the atmos monitor was tucked into the research tier for the scrubbers and freezers. Also bumped the cost a little.
**Changelog**
:cl:
- add: New boards to existing research options
- add: Said boards to the engineering lathe pack
> Power monitor(and atmos monitor) can be researched and printed

- Resources/Prototypes/Recipes/Lathes/Packs/medical.yml
- Resources/Prototypes/Recipes/Lathes/Packs/service.yml
- Resources/Prototypes/Recipes/Lathes/medical.yml
Currently just two recipes idk I tried making the department fabs researchable and craftable but it didn't work and I gave up lol
**Changelog**
:cl:
- add: Service fab has sterile swabs for .2 cloth and .2 steel
- add: Medical fab has walking canes for 1 steel, 2 wood
> Adding some recipes to the fabs

- Content.Client/Medical/CrewMonitoring/CrewMonitoringNavMapControl.cs
- Content.Client/Medical/CrewMonitoring/CrewMonitoringWindow.xaml.cs
- Content.Server/DeviceNetwork/Systems/SingletonDeviceNetServerSystem.cs
- Content.Server/Medical/SuitSensors/SuitSensorSystem.cs
- Resources/Prototypes/Entities/Clothing/Uniforms/base_clothinguniforms.yml
- Resources/Prototypes/Entities/Mobs/Player/admin_ghost.yml
- Resources/Prototypes/Entities/Objects/Misc/subdermal_implants.yml
- Resources/Prototypes/Entities/Structures/Machines/crew_monitor_server.yml
Suit sensor servers/consoles will now transceive across the entire map they are on.
Round removed because your suit's radio is blocked by the vacuum of space is bad.
Lightly based on Frontier's method of a similar change—suit sensors no longer care about their stationId, and instead just broadcast to all the servers on their map. The console originally just states your X and Y position on the station's grid, which isn't super helpful if you aren't on said grid, so the console now displays both the grid coordinates and the map coordinates of the selected user.
(The blip had blunk off at time of screenshot, but those work as expected.)
**Changelog**
:cl:
- add: Suit sensors and servers now have greatly increased range.
> Change suit sensors to be global across a server's map

- Resources/Prototypes/Catalog/Cargo/cargo_armory.yml
- Resources/Prototypes/Catalog/Fills/Crates/armory.yml
- Resources/Prototypes/Entities/Objects/Misc/subdermal_implants.yml
Fixes #109 
I would make implanters for both Med and Sec but the problem is that the implant adds a RattleComponent which only supports one channel and, as with any comp, you can only have one instance of.
I kept the armory access despite them being more of a Med item lore-wise because of balancing: There is currently no way to remove them, which makes them a bit of a privacy risk. The SA should at least tacitly approve implantation by unlocking the crate for Med. Maybe they could be made CMO access only in the future?
https://github.com/user-attachments/assets/c69d2db9-e5d7-408a-bb32-d668ecc1f1ea
**Changelog**
:cl:
- tweak: Tracking implants now speak on the Medical channel instead of the Security channel.
> Tracking implanters now report on Medical channel, updated lore

- Resources/Prototypes/Entities/Objects/Devices/Circuitboards/Machine/production.yml
- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Fixes #120
- "universal" because it makes a lot of different things and sounds sci-fi
- "textile" because it encompasses both uniforms, carpets, etc.
- "fabricator" because it's in line with other lathes (techfabs, exosuit fabricator, medical biofabricator)
"digital loom" is neat but I decided against it because a loom just weaves, but the uniform printer also does all the other steps.
**Changelog**
:cl:
- tweak: "Uniform Printer" renamed to "Universal Textile Fabricator", since it prints more than uniforms.
> Rename "uniform printer" to "universal textile fabricator"

- Content.Client/Administration/UI/CustomControls/AdminLogLabel.cs
- Content.Client/Cargo/UI/BountyHistoryEntry.xaml.cs
- Content.Client/CartridgeLoader/Cartridges/NewsReaderUiFragment.xaml.cs
- Content.Client/MassMedia/Ui/NewsArticleCard.xaml.cs
- Content.Client/PDA/PdaMenu.xaml.cs
- Content.Server/Administration/Systems/BwoinkSystem.cs
- Content.Server/GameTicking/GameTicker.GameRule.cs
- Content.Server/_DV/TapeRecorder/TapeRecorderSystem.cs
- Resources/ConfigPresets/Build/development.toml
Displays total days in addition to hours and minutes and seconds. Here is the exhaustive list:
- Entity log timestamps (these display a full real date in addition to the real time)
- Bounties consoles
- News (PDA and console)
- Shift duration (PDA)
- GameRule records
- Tape recorder printouts
- AHelp relay timestamps
Our rounds usually go longer than 24hours, and we would like for the game not to come apart at the seams when we do that!
- Completes #114.
- `TimeSpan.ToString()` does a modulo on hours, minutes, and seconds, but _not_ on days. Arbitrarily long shifts should simply display as the total number of days, plus `hh:mm:ss`.
- The format generally used in this PR prepends days and uses a dot separator. This maintains a relatively compact display, but is unambiguous as to where …
> Display days in round duration fields

- Content.Shared/_NF/Storage/EntitySystems/MaterialReclaimerMagnetPickupSystem.cs
- Content.Shared/_NF/Storage/EntitySystems/MaterialStorageMagnetPickupSystem.cs
- Resources/Locale/en-US/_NF/storage/components/magnet-pickup-components.ftl
- Resources/Prototypes/Entities/Structures/Storage/ore_box.yml
Essentially bringing them in line with ore bags: they can now hold artifact fragments, they magnetize in the same way (and it is toggable), and you can dump their contents on the ground.
Also makes the magnet enabled localization actually say a whole sentence.
Fixes #42.
It like ore bag.
**Changelog**
:cl:
- add: Ore boxes are now (optionally) magnetic, and can be dumped just like ore bags.
> Ore boxes now have magnets and are dumpable

- Resources/Prototypes/Entities/Objects/Devices/pda.yml
Psychologists are medically trained by their role, and thus should have medtek by default.
Resolves #186 
**Changelog**
:cl:
- tweak: Psychologist PDAs have MedTek installed by default.
> Psych PDAs inherit BaseMedicalPDA

- Resources/Prototypes/_DEN/Entities/Clothing/Neck/misc.yml
- Resources/Prototypes/_L5/Body/Organs/synth.yml
Apparently it's very easy and you can just scale: x, y in their prototypes. It's advised not to scale things up but downsizing seems fine? The sprites don't seem to mind unless I'm blind and missed some glaring defects caused by the scaling.
> Fixed the scaling on the synth brain and vet cone

- Content.Shared/_L5/Movement/Systems/PilotOnBuckleSystem.cs
- Resources/Locale/en-US/_L5/traits/traits.ftl
- Resources/Prototypes/_L5/Traits/disabilities.yml
Added collision behavior to wheelchairs
Reenabled wheelchairs as part of the low-mobility starting gear, and modified pilot-on-buckle system to automatically add collision to buckled entities.
**Changelog**
> Reenable & Add Collision to Wheelchairs

- Content.Shared/Telephone/TelephoneComponent.cs
Issue #258, far as I can tell it is literally just this value that determines it(and yes I checked in game and sat silent in a holocall for two minutes lmao).
Two minutes seems good enough but well, if it isn't it is dead easy to increase
> Doubled the time it takes for holopads to idle timeout

- Resources/Prototypes/_DV/Entities/Clothing/Eyes/glasses.yml
- Resources/Prototypes/_DV/Recipes/Construction/Graphs/clothing/glasses_corpshud.yml
Re-adds the security icons to corpsman glasses. Additionally requires security hud as a component in building corpsman glasses from the inventory.
To undo someone's 'balancing decision.'
**Changelog**
:cl:
- tweak: Returned corpsman glasses to their former glory.
> Reintroduce Security Icons to Corpsman Glasses

- Content.Shared/Preferences/Loadouts/Effects/JobRequirementLoadoutEffect.cs
- Content.Shared/Roles/JobRequirement/DepartmentTimeRequirement.cs
Disabled time requirements for loadouts.
They're dumb.
Fixes #89, as far as I know.
Partially addresses #119.
TECHNICALLY this also disables departmental time requirements, but we're always going to have that off via cvar anyway.
**Changelog**
:cl:
- remove: Loadout time requirements.
> feat: disable time requirements for loadouts

- Resources/Prototypes/Entities/Structures/Piping/Atmospherics/miners.yml
Make miners unanchorable.
Silly RCD meme to unanchor them is silly.
**Changelog**
- add: You can now unanchor gas miners.
> feat: allow miners to just be unanchorable

- Resources/ConfigPresets/L5/outpost.toml
> fix: don't speedrun restarting

- Content.Server/Radio/EntitySystems/RadioDeviceSystem.cs
- Content.Server/_L5/Radio/RadioDeviceSystem.cs
Made radio microphones ignore speech that would've been obfuscated due to distance.
Radios working good.
**Changelog**
:cl:
- fix: Radios no longer pick up obfuscated speech
> fix: radios shouldn't pick up obfuscation

- Content.Server/_L5/Traits/DietaryRestriction/DietaryRestrictionSystem.cs
- Content.Shared/_L5/Traits/DietaryRestriction/DietaryRestrictionComponents.cs
- Resources/Locale/en-US/_L5/traits/traits.ftl
- Resources/Prototypes/Body/Organs/moth.yml
- Resources/Prototypes/Body/Organs/reptilian.yml
- Resources/Prototypes/_L5/Traits/restricted_diet.yml
- Resources/Prototypes/_L5/dietary_restrictions.yml
By default, moths and lizards can eat everything, but now anyone can select their diets as a trait
This is the type of thing that was probably thought about pretty early on.
It still currently shows the doafter, but it fails at the end without consuming. It should at least show the fail message.
**Changelog**
:cl:
- tweak: Lizard and moth diets are now traits rather than species specific; anyone can take them!
> Move moth and reptilian diets to traits

- Content.Server/Atmos/Monitor/Systems/AirAlarmModes.cs
- Content.Shared/_L5/Atmos/GasVentPumpData.cs
Fill and panic were... modifying reference types.
Why is GasVentPumpData not a struuuuct gaahhhhhh.
**Changelog**
> fix: air alarm panic/fill flowmos presets unborken

- Resources/Locale/en-US/traits/traits.ftl
we cool, perry said i should upstream the monochromacy typo fix  but like... im lazy so???
**Changelog**
:cl:
- tweak: It's monochromacy, not monochromancy 
- tweak: Muted is now non-speaking
> Small change to the muted trait, fixed a typo in another trait

- Resources/Prototypes/_Nuclear14/Entities/Structures/Misc/floradesert.yml
Fixes N14 tree hitboxes and sprite offsets.
Hitboxes aren't supposed to be like 3.5 tiles away from the part that you would run into. Seriously that's how far off some of these were.
Guess which is before and which is after.
**Changelog**
nah
> fix: make N14 tree hitboxes make sense

- Resources/Prototypes/_L5/Entities/Structures/Machines/foodfridge.yml
I thought produce had the food component, missed this in testing.
**Changelog**
:cl:
- fix: FoodMate fridges can now accept raw produce.
> fix: Missing whitelist component added to food fridge
